/**
 * In-app auto-update via electron-updater + GitHub Releases.
 *
 * The user clicks "Check for updates" in Settings. We query the GitHub
 * provider, compare versions, and emit events the renderer listens to.
 *
 * If a new version exists the user can hit "Download" — electron-updater
 * fetches the .exe + .blockmap into appData/Updates/, verifies it via
 * latest.yml, then "Install & restart" runs `quitAndInstall()` which fires
 * the NSIS installer in update mode (no UI prompts) and re-launches the new
 * version. No manual uninstall / reinstall.
 */

import { app, BrowserWindow } from 'electron';
import pkg from 'electron-updater';
import type { UpdateStatus } from '@shared/types';

// CommonJS interop for electron-updater (it ships dual)
const { autoUpdater } = pkg;

let lastStatus: UpdateStatus = { phase: 'idle' };
let initialized = false;

function broadcast(status: UpdateStatus): void {
  lastStatus = status;
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) {
      win.webContents.send('updater.status', status);
    }
  }
}

export function getUpdateStatus(): UpdateStatus {
  return lastStatus;
}

export function getCurrentVersion(): string {
  return app.getVersion();
}

function ensureInit(): void {
  if (initialized) return;
  initialized = true;

  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = false;
  // GitHub publishing config is taken from the build's app-update.yml (auto-
  // generated by electron-builder from electron-builder.yml `publish:` block).

  autoUpdater.on('checking-for-update', () => {
    broadcast({ phase: 'checking', currentVersion: app.getVersion() });
  });

  autoUpdater.on('update-available', (info) => {
    broadcast({
      phase: 'available',
      currentVersion: app.getVersion(),
      latestVersion: info.version,
      releaseNotes:
        typeof info.releaseNotes === 'string'
          ? info.releaseNotes
          : undefined,
      releaseDate: info.releaseDate,
    });
  });

  autoUpdater.on('update-not-available', (info) => {
    broadcast({
      phase: 'up-to-date',
      currentVersion: app.getVersion(),
      latestVersion: info.version,
    });
  });

  autoUpdater.on('error', (err) => {
    broadcast({
      phase: 'error',
      currentVersion: app.getVersion(),
      error: err instanceof Error ? err.message : String(err),
    });
  });

  autoUpdater.on('download-progress', (p) => {
    broadcast({
      phase: 'downloading',
      currentVersion: app.getVersion(),
      latestVersion: lastStatus.latestVersion,
      progress: {
        percent: p.percent,
        bytesPerSecond: p.bytesPerSecond,
        transferred: p.transferred,
        total: p.total,
      },
    });
  });

  autoUpdater.on('update-downloaded', (info) => {
    broadcast({
      phase: 'downloaded',
      currentVersion: app.getVersion(),
      latestVersion: info.version,
    });
  });
}

export async function checkForUpdates(): Promise<UpdateStatus> {
  ensureInit();
  if (!app.isPackaged) {
    const info: UpdateStatus = {
      phase: 'error',
      currentVersion: app.getVersion(),
      error:
        'Auto-updater is only available in packaged builds. ' +
        'Run the installed .exe (not the dev mode) to test updates.',
    };
    broadcast(info);
    return info;
  }
  try {
    await autoUpdater.checkForUpdates();
  } catch (err) {
    broadcast({
      phase: 'error',
      currentVersion: app.getVersion(),
      error: err instanceof Error ? err.message : String(err),
    });
  }
  return lastStatus;
}

export async function downloadUpdate(): Promise<UpdateStatus> {
  ensureInit();
  if (!app.isPackaged) {
    return {
      phase: 'error',
      currentVersion: app.getVersion(),
      error: 'Cannot download updates in dev mode.',
    };
  }
  try {
    await autoUpdater.downloadUpdate();
  } catch (err) {
    broadcast({
      phase: 'error',
      currentVersion: app.getVersion(),
      error: err instanceof Error ? err.message : String(err),
    });
  }
  return lastStatus;
}

export function quitAndInstall(): void {
  ensureInit();
  if (!app.isPackaged) return;
  // `isSilent=false`: NSIS shows its own progress UI as the installer runs;
  // `isForceRunAfter=true`: re-launch Devliz as the new version automatically.
  autoUpdater.quitAndInstall(false, true);
}
